baseURL: 'https://mineo-engine.com/'
title: 'mineoの技術ブログ的な何か'
author: mineo

languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
theme: hugo-PaperMod

googleAnalytics: G-NGSW461B9F

pagination:
  pagesize: 5

params:
  ShowReadingTime: false
  contentTypeName: posts
  defaultTheme: auto
  ShowShareButtons: false
  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: '#'
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  assets:
    favicon: "/assets/favicon.ico"
    favicon16x16: "/assets/favicon-16x16.png"
    favicon32x32: "/assets/favicon-32x32.png"
    apple_touch_icon: "/assets/apple-icon.png"

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: 'mineoが書く技術ブログ的な何かです'

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/MinusEke'
    - name: github
      url: 'https://github.com/EkeMinusYou'

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1

menu:
  main:
    - name: Archives
      url: /archives/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 10
    - name: Series
      url: /series/
      weight: 15

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true