name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install hugo && hugo
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_REGION }}
      - run: aws s3 sync ./public/ s3://${{ secrets.S3_BUCKET }} --delete